### ISSUE TITLE
[BUG] AttributeEror: fedavg_cs.Server has no 'do_edge_test'

### ISSUE THREAD

**Issue by cuiboyuan** [TL-System/plato#142]
**Describe the bug**
In `__init__()` of class `Server` in file **plato/servers/fedavg_cs.py**, the function uses attribute `self.do_edge_test` at line 38 which is not defined previously.

**To Reproduce**
1. Run any of the following examples that use the class `fedavg_cs.Server`:
- `examples/axiothea/axiothea.py`
- `examples/cs_maml/cs_maml.py`
- `examples/rhythm/rhythm.py`
- `examples/tempo/tempo.py`
2. See AttributeError

**Expected behavior**
No error should be raised when running these examples

**Screenshots**
```
[INFO][15:51:14]: [Server #18644] Started training on 1 clients with 1 per round.
Traceback (most recent call last):
  File "\plato-project-home\examples\tempo\tempo.py", line 19, in <module>
    main()
  File "\plato-project-home\examples\tempo\tempo.py", line 11, in main
    server = tempo_server.Server()
  File "\plato-project-home\examples\tempo\tempo_server.py", line 20, in __init__
    super().__init__()
  File "\plato-project-home\plato\servers\fedavg_cs.py", line 38, in __init__
    and not self.do_edge_test):
AttributeError: 'Server' object has no attribute 'do_edge_test'
```

**OS environment:**
 - OS: Windows 10 64-bit
 - Using Python 3.9
 - Using IDE PyCharm Community Edition 2021.3

**Additional context**
none

**Comment by cuiboyuan** [comment]
The error has been successfully resolved by PR #147 . Closing
