### ISSUE TITLE
[RuntimeError]: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by XinYao1994** [TL-System/plato#91]
**Describe the bug**
The bug happens during the training process on the client. The information is "expected scalar type Half but found Float".

**To Reproduce**
Steps to reproduce the behavior in CPU-only cluster:
1. ```./run -c configs/YOLO/fedavg_yolov5.yml```
2. ```./run -c configs/YOLO/mistnet_yolov5.yml```  <- happens at this phase.
3. Output shows:
```
[INFO][09:27:57]: Training on client #0 failed.
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "plato/plato/trainers/basic.py", line 199, in train_process
    raise training_exception
  File "plato/plato/trainers/basic.py", line 109, in train_process
    self.train_model(config, trainset, sampler.get(), cut_layer)
  File "plato/plato/trainers/yolo.py", line 182, in train_model
    pred = self.model.forward_from(imgs, cut_layer)
  File "plato/plato/models/yolo.py", line 67, in forward_from
    x = m(x)  # run
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/python3.8/site-packages/yolov5/models/common.py", line 138, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/python3.8/site-packages/yolov5/models/common.py", line 42, in forward
    return self.act(self.bn(self.conv(x)))
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: expected scalar type Half but found Float
```

**Expected behavior**

**OS environment (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**

**Comment by baochunli** [comment]
@TrackerLB It is mostly due to an outdated model code (used an old version of YOLOv5) for the forward_from() implementation. Since you wrote this code, can you take a look?

**Comment by TrackerLB** [comment]
@baochunli OK.
