### ISSUE TITLE
[Bug] Running Custom Dataset need to import tensorflow_datasets

### ISSUE THREAD

**Issue by XinYao1994** [TL-System/plato#99]
**Describe the bug**
Running Custom Dataset need to import tensorflow_datasets

**Screenshots**
It seems that there are several unnecessary dependencies when the user configures its own dataset and load from ```base.Datasource```.
```
Traceback (most recent call last):
  File "aggregate.py", line 35, in <module>
    run_server()
  File "aggregate.py", line 29, in run_server
    chooser=simple_chooser)
  File "/home/lib/sedna/service/server/aggregation.py", line 325, in __init__
    from plato.servers import registry as server_registry
  File "/home/plato/plato/servers/registry.py", line 10, in <module>
    from plato.servers import (
  File "/home/plato/plato/servers/fedavg.py", line 11, in <module>
    from plato.algorithms import registry as algorithms_registry
  File "/home/plato/plato/algorithms/registry.py", line 23, in <module>
    from plato.algorithms.tensorflow import (
  File "/home/plato/plato/algorithms/tensorflow/fedavg.py", line 7, in <module>
    from plato.datasources import registry as datasources_registry
  File "/home/plato/plato/datasources/registry.py", line 19, in <module>
    from plato.datasources.tensorflow import (
  File "/home/plato/plato/datasources/tensorflow/mnist.py", line 5, in <module>
    import tensorflow_datasets as tfds
ModuleNotFoundError: No module named 'tensorflow_datasets'
```

**OS environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Version 20.04

**Comment by XinYao1994** [comment]
**Running TensorFlow should work without the installation of Pytorch**
This has been solved by placing ```use_tensorflow``` flag before loading the server_registry
```
2021-09-10 04:21:54.195254: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2600000000 Hz
2021-09-10 04:21:54.195554: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3ff50c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-10 04:21:54.195571: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "aggregate.py", line 35, in <module>
    run_server()
  File "aggregate.py", line 29, in run_server
    chooser=simple_chooser)
  File "/home/lib/sedna/service/server/aggregation.py", line 279, in __init__
    from plato.servers import registry as server_registry
  File "/home/plato/plato/servers/registry.py", line 10, in <module>
    from plato.servers import (
  File "/home/plato/plato/servers/fedavg.py", line 11, in <module>
    from plato.algorithms import registry as algorithms_registry
  File "/home/plato/plato/algorithms/registry.py", line 30, in <module>
    from plato.algorithms import (
  File "/home/plato/plato/algorithms/mistnet.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

2021-09-10 04:34:51.958257: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4380290 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-10 04:34:51.958286: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "aggregate.py", line 35, in <module>
    run_server()
  File "aggregate.py", line 29, in run_server
    chooser=simple_chooser)
  File "/home/lib/sedna/service/server/aggregation.py", line 279, in __init__
    from plato.servers import registry as server_registry
  File "/home/plato/plato/servers/registry.py", line 10, in <module>
    from plato.servers import (
  File "/home/plato/plato/servers/fedavg.py", line 13, in <module>
    from plato.datasources import registry as datasources_registry
  File "/home/plato/plato/datasources/registry.py", line 28, in <module>
    from plato.datasources import (
  File "/home/plato/plato/datasources/mnist.py", line 4, in <module>
    from torchvision import datasets, transforms
ModuleNotFoundError: No module named 'torchvision'
```

**Comment by baochunli** [comment]
The current MistNet implementation does not support TensorFlow; it supports PyTorch only. Only FedAvg supports TensorFlow at this time.
